kind: PersistentVolume
apiVersion: v1
metadata:
  name: psql-pv
  labels:
    app: psql-label
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data/psql