kind: Secret
apiVersion: v1
metadata:
  name: lms-secrets
  namespace: lms-ns

data:
    SECRET_KEY: cFptbnRTY3NIeWdEWURLZWFyVHRKckppRHFyb0hWSE9Fd2o1TjZ1VDdaTWpPQWFjc2d6RlptbVdWSGFSWFFLaVFqNzJ2WGFYL0dBZTBEbjA3SjFUTXc9PQ==
    ADMIN_PASSWORD: Z3pGWm1tV1ZIYVJYUUtpUWo3MnZYYQ==
    POSTGRES_PASSWORD: c2VudCFuM2w=


