apiVersion: v1
kind: Service
metadata: 
  name: psql-svc
  namespace: lms-ns
spec:
  selector:
    app: psql-label
  ports:
    - port: 5432
---
apiVersion: v1
kind: Service
metadata: 
  name: backend-svc
  namespace: lms-ns
spec:
  selector:
    app: backend-label
  ports:
    - port: 8000
---
apiVersion: v1
kind: Service
metadata: 
  name: frontend-svc
  namespace: lms-ns
spec:
  selector: 
    app: frontend-label
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
    - port: 80
      nodePort: 30080
  type: NodePort